# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('plato', models.ManyToManyField(blank=True, to='Plato.Plato')),
            ],
        ),
    ]
